name: flutter_login_demo
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  carousel_slider: ^2.2.1
  cloud_firestore: ^0.13.0+1
  google_maps_flutter: ^0.4.0
  url_launcher: ^5.5.0
  firebase_storage:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/flutter-icon.png
